

spring:
  datasource:
    username: root
    password: 6154898
    url: jdbc:mysql://localhost:3306/my_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations:
  - classpath*:/com/msb/dongbao/ums/mapper/xml/*.xml
  type-aliases-package: com.msb.dongbao.ums.entity
server:
  port: 8081
